server:
  port: 8082
spring:
  application:
    name: order-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall_db?useSSL=false&characterEncoding=utf8
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8718   # sentinel 控制台地址
      eager: true                   # 取消懒加载，启动即注册
feign:
  sentinel:
    enabled: true                   # 开启feign对sentinel的支持

seata:
  tx-service-group: my_test_tx_group # 事务分组名，可以自定义
  registry:
    type: nacos
    nacos:
      server-addr: localhost:8848
      group: SEATA_GROUP
      namespace: ""
      username: "nacos"
      password: "nacos"
  service:
    vgroup-mapping:
      my_test_tx_group: default # 将事务分组映射到 Seata 集群